apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: ClusterIP # Доступен только внутри кластера (пока что)
  selector:
    app: vote # ВАЖНО: Service ищет поды с этой меткой!
  ports:
    - port: 80        # Порт сервиса
      targetPort: 80  # Порт контейнера (из Deployment)