name: CyberArena CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: justboy420/cyberarena-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.8.0

      - name: Load image into Kind
        run: |
          kind load docker-image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --name chart-testing

      - name: Deploy to Kubernetes
        run: |
          sed -i 's|ghcr.io/justboy420/cyberarena-app:latest|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g' k8s/vote-deployment.yaml
          kubectl apply -f k8s/vote-deployment.yaml
          kubectl rollout status deployment/cyberarena-frontend --timeout=60s

      - name: Test Deployment
        run: |
          kubectl port-forward svc/cyberarena-svc 8080:80 &
          sleep 5
          RESPONSE=$(curl -s http://localhost:8080)
          echo "Response from K8s: $RESPONSE"
          if echo "$RESPONSE" | grep -q "CyberArena"; then
            echo "✅ HEALTH CHECK PASSED!"
          else
            echo "❌ HEALTH CHECK FAILED!"
            exit 1
          fi
