name: OpenTofu IaC Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tofu:
    runs-on: ubuntu-latest
    name: Run OpenTofu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        run: tofu init
        working-directory: ./iac

      - name: OpenTofu Plan
        run: tofu plan
        working-directory: ./iac
        # Пока что мы делаем только plan, чтобы не создавать реальную инфру в GitHub